### ISSUE TITLE
ディレクトリ構造を変えたい

### ISSUE THREAD

**Issue by ybrliiu** [kasetsubaby/kasetsu#19]
現在プロジェクトルートにcgiファイルが散らばっており、これからいろんなファイルを追加することを考えると管理しづらいのでディレクトリ構造を変えたいです。
標準的なPerlプロジェクトのディレクトリ構造を参考に変えるといいかなと思っています。

案
- scripts/ ... cgiファイルとか突っ込むところ
- lib/ ... ライブラリファイルを突っ込むところ
- t/... テストファイルを突っ込むところ

**Comment by ybrliiu** [comment]
test

**Comment by ybrliiu** [comment]
@kasetsubaby こちらどう思われますか・・・？

**Comment by kasetsubaby** [comment]
反応遅くてすみません。
良いと思います。
@ybrliiu

**Comment by ybrliiu** [comment]
ありがとうございます。
